version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss
    ports:
      - "4545:3000"  # Maps host port 4545 to Grafana's default container port 3000
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge