global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'ocrpro.ai'
    scheme: https
    metrics_path: /api/core/metrics
    static_configs:
      - targets: ['ocrpro.ai']
    tls_config:
      server_name: 'https://ocrpro.ai'
      insecure_skip_verify: true
      
