global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'ocrpro.ai'
    scheme: http
    metrics_path: /api/core/metrics
    static_configs:
      - targets: ['ocrpro.ai']
    tls_config:
      insecure_skip_verify: true